apiVersion: apps/v1
kind: Deployment
metadata:
  name: libro-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libro-mongodb
  template:
    metadata:
      labels:
        app: libro-mongodb
    spec:
      containers:
      - name: libro-mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc 